add hooks to capture event and entity names as they are registered
aaronkirkham/jc4-console-thingy pull request #1
Opened 2018-12-22 01:21 UTC by pcgrosen

Add a hook in the event registration function in order to capture events for autocompletion in the console.

Additionally, add a hook in the property file parser for spawnable objects in order to capture both entity names and "spawn specifiers" for autocomplete. In particular, users can choose which set to show hints from: by default, show hints from entity names, but, if the arguments begin with a `!`, parse the string into its corresponding specifiers (handled by the game at 0x140A083DE, though reimplemented in this commit), and display suggestions from the set of specifiers that correspond to the currently-possible entities.

Definitely open to suggestions on the code; this is my first even-remotely-serious C++ project!

2018-12-22 19:28 UTC, aaronkirkham requested changes
Hey, thanks for this! This is definitely something I originally wanted to do but was hooking in the wrong places to get a full list of models.

I have reviewed everything and played with it a little in game and it works well and is definitely better than managing an array of model names by hand.

There are a few minor code changes to be made and also some ideas about the `!` spawn prefix which would be great to get your thoughts on.

2018-12-22 19:28 UTC, aaronkirkham commented on src/commands/event.h
> +        add_event_hook.inject(AddEvent);
Would prefer lambda here, instead of a static class method - this way we can use `add_event_hook.call(...)` to invoke the original function instead of the `hk::func_call` in AddEvent. Makes life a little easier when maintaining addresses on version changes. (See [main.cpp](https://github.com/aaronkirkham/jc4-console-thingy/blob/master/src/main.cpp#L97))

2018-12-22 19:28 UTC, aaronkirkham commented on src/commands/spawn.h
> +        add_event_hook.inject(AddModelName);
Same as event.h comment. Prefer lambda.

2018-12-22 19:28 UTC, aaronkirkham commented on src/commands/spawn.h
> +        if (arguments.length() > 0 && arguments.at(0) == '!') {
I'm 50/50 about the specifiers thing. I think if you are spawning something, you probably have an idea of the thing you want to spawn, which should be easy enough to find in the full_model_name hints. As far as I know the game uses the specifiers to spawn random things based on its tags, e.g. `character,rebel` would pick a random rebel character to spawn.

Maybe a compromise here is to only have hints of full_model_names, but allow searching for full_model_name and specifiers. So searching for `character,rebel` would show a list of full_model_name hints which have the specifiers attached to it. That way we don't have to explicitly type the `!` prefix.

2018-12-22 19:28 UTC, aaronkirkham commented on src/commands/spawn.h
> +    struct PropertyFileEntry {
```suggestion
#pragma pack(push, 1)
     struct PropertyFileEntry {
```
While it's not a huge issue, because you're using a pointer to this struct in `PropertyFileResult`, I think doing this now and preventing any bugs related to it in the future is a good idea.

2018-12-22 19:28 UTC, aaronkirkham commented on src/commands/spawn.h
> +    };
```suggestion
    };
#pragma pack(pop)
```
Closing for above `push`.

2018-12-22 19:28 UTC, aaronkirkham commented on src/commands/spawn.h
> +        if (arguments.length() == 0) {
We should filter out a few models such as `rico_debug`, `rico_preview_debug`, `rico_cow_skin`, `rico_cow_skin_debug`. While most of these don't seem to do anything, `rico_preview_debug` definitely does try to spawn and will crash the game and corrupt save game data (found out the hard way). (See [event.h](https://github.com/aaronkirkham/jc4-console-thingy/blob/master/src/commands/event.h#L31))

2018-12-23 08:49 UTC, pcgrosen commented on src/commands/spawn.h
> +        if (arguments.length() > 0 && arguments.at(0) == '!') {
I agree that spawning by model name is by far most common; that's why I left it as the default. However, I certainly do see use-cases for specifiers. For example, I've been messing around with keybinds for commands on a local branch, and I enjoy being able to spawn a varied army by binding a key to `spawn !character,military`.

With regards to your suggestion, I think we lose a lot of usability by removing the specifier hints. Part of what I find so useful about them is being able to slowly narrow down through the hierarchy (of more general specifiers to more specific), but if we don't display the next valid specifiers, that's very difficult to do.

I guess what I would consider the "optimal" solution would be to display both at the same time in the hint and allow the user to pick which one to use inside of the choose-hint functionality, but of course that would require a rework of that system.

In my opinion, the `!` override seems like the ideal solution (barring a rework of the hints): it keeps the most common use-case (entity names) unchanged, but still provides a simple method to switch to specifiers if desired.

What do you think?

2018-12-24 17:58 UTC, aaronkirkham commented
Thanks for the changes.

After playing a bit more with it I'm happy with the model/specifier stuff, I guess it's a feature that is there if you need it and might be useful for some people.

Now my only issue is with the events hints list as it seems 90% of the registered ones have no effect at all (lots of `hinge_node_x`) and some causing crashes. Maybe it would just be better to just keep this as it was and just maintain a list of tried-and-tested working event names? I feel like the amount of only working, useful events is small enough for that.

Let me know what you think.

2019-08-15 19:21 UTC, closed without merging